### PR TITLE
[WIP] Add sleep before spin attempt (Ref: Issue #275)

### PR DESCRIPTION
**Pull request by cptmedic**
This pull request is being proposed in regards to issue #275 as sleeping after the jitter of accounts seems to reduce the failure rate of spins. It adds a random_sleep between 4 and 5.5 seconds after jittering location. This appears to reduce the failure to spin pokestops. From a few personal tests and another users tests it seems to increase the rate of successful spins.

### CODE REVIEW

**Comment by mewio** [comment]
4-5.5 seconds seems like a long time to render a worker inactive, especially considering that we don't know the root cause of the problem.

For comparison, I saw significant improvement when I reduced spin_pokestop()'s range from 36 to 26 and added a random sleep of only 1.8-2.1 seconds. This implies to me that, at the very least, we could minimize time wasted in sleep() by spinning the closest pokestop first when several are nearby.

I feel like committing this PR right now would be premature, since more experimentation could reveal how to get better results.

**Comment by captainmedic** [comment]
What percentages pass/fail were you having, I do not believe I saw any success/fail reported by you and thus based on mine and the other users success improving by a longer wait time I suggested this. I am open assuming pass percentage is the same or better, else I am fine with workers resting a whole 2 seconds more.

**Comment by captainmedic** [comment]
Ok, so I do agree reducing the distance from a pokestop a worker is does indeed increase the passing percentage, currently at 15 minutes of scanning, accounts have spun roughly 800 stops, and have an average success of 79%. I am going to test out a couple more settings, and see how this changes.

**Comment by evenly-epic-mule** [comment]
I've been preparing something simular, which should be a more generic solution

**Comment by captainmedic** [comment]
Just wanted to share another brief experiment with the numbers.

82% pass with 377 total attempts to spin - distance 26
79.9% 303 total attempts - distance 26
91.3% with 173 total attempts to spin - distance 16
90.7% with 226 total attempts to spin -  - distance 16
Speed for all tests were set at random 1.8->2.1

**Comment by evenly-epic-mule** [comment]
well I think one main issue here is how far was the last location away
so we may receive very different results as sizes of maps vary

**Comment by mewio** [comment]
We're getting off-topic for a PR. I suggest moving this discussion back to issue #275.

**Pull request closed without merging**
