### PR TITLE
Raids+Gymplus(Names and images, Defenders)

### PR DESCRIPTION
**Pull request by MonkeyTedBaker**
This is an extension to my another pull request #324 

On top of providing raid information, it also provides
* Fort and Pokéstop name and image updates (only once each)
* Adding gym_defenders
  * smart throttled (same as incubation)
  * GET_GYM_DETAILS flag to turn on/off scanning gym details
  * GYM_COOLDOWN flag to set worker rest time after scanning gym details
* Eradicated prestige
* Prioritized updating of gym details. See wiki 👇
https://github.com/MonkeyTedBaker/Monocle/wiki/Prioritized-gym-details
---
> Make sure to set the following in config.py 👇
```
# Default False
GET_GYM_DETAILS = True

 # Seconds to wait for a worker between two gym scans. Default 180 seconds. Adjust according to your needs.
GYM_COOLDOWN = 180
```
# Migration

1. Run `sql/gymplus.sql` on your DB.
2. Run `python3 scripts/create_db.py`.

# Unicode names support

If you are having problem with unicode related error, make sure to set your DB charset as utf8 in `config.py`.

E.g. for mysql,

```
DB_ENGINE = "mysql://user:pass@host:port/db?charset=utf8" # or charset=utf8mb4
```

# Frontend

Sorry. I don't intend to implement frontend changes.
If you are willing to contribute, please give me a pull request.

### CODE REVIEW

**Comment by georgeherby** [comment]
I have been running this for the last 24 hours and i noticed that because of the gym cool down it only gets the gym details for the first gym that it get the details for in the map_cell.forts.

The reason i spotted this is that i wanted to have the Gym name on raid notifications using webhook. I added `'fort_name': fort['name'],` to notify_raid in notifcation.py but this often returned no value for fort['name'] and thus an error.

The only work around that i could find (im sure not the best or the only way) for this was to add the following inside `if fort not in RAID_CACHE:` within the worker.py
```
gym = await self.gym_get_info(normalized_fort)
if gym:
     self.log.info('Got gym info for (raid edition) {}', normalized_fort["name"])
```


This is the full snippet for that part of the code:
```
                else:
                    normalized_fort = self.normalize_gym(fort)
                    if fort not in FORT_CACHE:
                        self.log.info('Not in Fort Cache')
                        if (self.gyms and time() > self.next_gym):
                            self.log.info("Name will be returned")
                            gym = await self.gym_get_info(normalized_fort)
                            if gym:
                                self.log.info('Got gym info for {}', normalized_fort["name"])
                            db_proc.add(normalized_fort)
                        else:
                            self.log.info("No Name will be returned")
                            db_proc.add(normalized_fort)
                    if fort.HasField('raid_info'):
                        self.log.info('Processing Raid')
                        #self.log.info('Processing Raid for {}', normalized_fort["name"])
                        if fort not in RAID_CACHE:
                            normalized_raid = self.normalize_raid(fort)

                            gym = await self.gym_get_info(normalized_fort)
                            if gym:
                                self.log.info('Got gym info for (raid edition) {}', normalized_fort["name"])

                            if (notify_conf and normalized_raid['pokemon_id'] > 0
                                    and normalized_raid['time_end'] > int(time())
                                    and self.notifier.eligible(normalized_raid)):
                                LOOP.create_task(self.notifier.notify_raid(normalized_raid, normalized_fort, map_objects.time_of_day))
                            db_proc.add(normalized_raid)
```

I may be misunderstanding how this works but something i thought would be a good thing to have.

**Comment by phonezawphyo** [comment]
@georgeherby Did some tweaks to improve performance and decrease hashing usage while solving your problem. Check it out!

While you are there, you might wanna check out my wiki and develop branch as well.
Have a good day.

**Comment by MonkeyTedBaker** [comment]
@georgeherby Did some tweaks to improve performance and decrease hashing usage while solving your problem. Check it out!

While you are there, you might wanna check out my wiki and develop branch as well.
Have a good day.

**Comment by georgeherby** [comment]
@MonkeyTedBaker yeah I saw your develop branch so i have pulled that and will see if it all works

**Comment by M3G4THEKING** [comment]
@MonkeyTedBaker check travis  and good work i like it 👍

**Comment by rileypool** [comment]
PostgreSQL syntax for Encoding issues: 
`DB_ENGINE = 'postgresql://user:pass@localhost/database?client_encoding=UTF8`

**Pull request closed without merging**
