### PR TITLE
Several Infos improvement,Label map,pokestop info ,gym info and pokemom

### PR DESCRIPTION
**Pull request by m3g4mInD**
Added Gym Info:
Team Name
Prestige : Total xp
Guarding Pokemon Name and id
Location 
Get directions url google maps

Added Pokestop info:
Location
Get directions url google maps

Pokemon info:

Pokemon Name
Location
Get directions url google maps

All tested by on my map in windows 10 and Ubuntu 14.04

Last Developer Branch. 
Date: 16/01/2017

### CODE REVIEW

**Comment by shockler** [comment]
@m3g4mInD can you fix the conflict :(

**Comment by m3g4mInD** [comment]
Yes i gonna fix thanks

**Comment by m3g4mInD** [comment]
I  need to check something and maybe change some code about layers,after i sleep :)

**Comment by m3g4mInD** [comment]
Git in my windows 10 as rip me off,i close this #pr but i open a update pull request.  [https://github.com/Noctem/pokeminer/pull/42](url)

**Pull request closed without merging**
